### ISSUE TITLE
Fazer cadastro

### ISSUE THREAD

**Issue by leonardo-kazu** [HUMAP-FireAlert/docs#1]
Como brigadista do hospital, gostaria de poder cadastrar uma conta na aplicação, para ter acesso às suas funcionalidades.

**Critérios de aceitação:**

- Deve ser possível criar uma nova conta de brigadista na aplicação, inserindo as informações necessárias:
> - Nome completo;
> - Email;
> - Telefone para contato;
> - Setor;
> - Senha.

- Se o email fornecido já estiver cadastrado na base de dados de brigadistas, o acesso deve ser liberado instantaneamente.

- Se o email não estiver cadastrado, o cadastro deve ser submetido para uma tabela separada para futuro gerenciamento.

- O cadastro do usuário deve ser armazenado com segurança no banco de dados.

- O usuário deve receber feedback claro sobre o estado do cadastro, seja ele bem-sucedido ou mal-sucedido.

- As telas de cadastro devem estar disponíveis quando solicitadas pelo usuário.

- As telas de confirmação de cadastro devem estar disponíveis quando o cadastro for concluído.

- Se meu email já estiver cadastrado na base de dados de brigadistas cadastrado, meu acesso deve ser liberado instantaneamente, caso contrario devo aguardar o chefe da brigada aprovar meu cadastro manualmente futuramente.

Tasks:

- [x] [Criar tabela no banco de dados](https://github.com/HUMAP-FireAlert/backend/issues/2)
- [x] [Criar endpoint para receber e processar as informações de cadastro do usuário](https://github.com/HUMAP-FireAlert/backend/issues/3)
- [x] [Implementar a tela de cadastro e confirmação de cadastro (app)](https://github.com/HUMAP-FireAlert/app/issues/4)
