### ISSUE TITLE
Disparar alerta interno

### ISSUE THREAD

**Issue by leonardo-kazu** [HUMAP-FireAlert/docs#10]
Como membro da equipe de liderança, desejo ter a opção de disparar um alerta interno a partir de uma ocorrência que eu julgue necessitar de atenção especial. Dessa forma, poderei criar uma chamada entre todos os membros da equipe para essa ocorrência em específico e garantir que um (e somente um) deles assuma a responsabilidade por ela.

Para isso eu devo clicar em um botão de disparar alerta interno na tela de tratamento de ocorrência, após isso devo ser encaminhado para confirmação de envio #11.

**Critérios de aceitação:**

- Deve haver um botão ou opção clara para disparar o alerta interno;
- Todos os membros da equipe devem ser notificados imediatamente;
- A ocorrência que gerou o alerta deve ser claramente descrita na mensagem de notificação;
- Cada membro da equipe deve confirmar ou recusar sua disponibilidade para assumir a responsabilidade pela ocorrência antes que outra pessoa possa fazê-lo;
- Somente um membro da equipe pode assumir a responsabilidade pela ocorrência geradora do alerta interna;
- O sistema deve registrar quem assumiu a responsabilidade pela ocorrência e quando isso ocorreu.

**Tasks:**

- [x] Criar botão de disparar alerta interno na tela de tratamento de ocorrência (app).
- [x] Configurar notificação imediata para todos os membros da equipe selecionados quando o alerta for disparado (backend).
- [x] Incluir a descrição clara da ocorrência geradora do alerta na mensagem de notificação (backend).
