### ISSUE TITLE
Confirmar/Cancelar envio do alerta

### ISSUE THREAD

**Issue by leonardo-kazu** [HUMAP-FireAlert/docs#11]
Como membro da equipe de liderança, desejo ter a opção de confirmar ou cancelar o envio do alerta interno após clicar no botão de disparo, para evitar que alertas indesejados sejam enviados. Dessa forma, poderei garantir que apenas as ocorrências realmente importantes e que exigem atenção especial sejam comunicadas à equipe.

**Critérios de aceitação:**

- Deve haver uma tela de confirmação clara após o clique no botão de disparo do alerta;
- Se o usuário confirmar o envio do alerta, todos os membros da equipe selecionados devem ser notificados imediatamente;
- A ocorrência que gerou o alerta deve ser claramente descrita na mensagem de notificação;
- Cada membro da equipe deve confirmar ou recusar sua disponibilidade para assumir a responsabilidade pela ocorrência antes que outra pessoa possa fazê-lo;
- Somente um membro da equipe pode assumir a responsabilidade pela ocorrência geradora do alerta interna;
- O sistema deve registrar quem assumiu a responsabilidade pela ocorrência e quando isso ocorreu.

**Tasks:**

- [x] Implementar tela de confirmação após o clique no botão de disparo do alerta (app);
- [x] Configurar sistema que permita o cancelamento do envio do alerta caso ele tenha sido disparado por engano ou não seja necessário (backend);
- [x] Configurar notificação imediata para todos os membros da equipe selecionados quando o alerta for disparado (backend);
