### ISSUE TITLE
Criar alerta interno

### ISSUE THREAD

**Issue by leonardo-kazu** [HUMAP-FireAlert/docs#12]
Como membro da equipe de liderança, desejo ter a opção de criar um alerta interno preenchendo um formulário específico, para que possamos comunicar uma ocorrência importante mesmo que ela não tenha sido gerada por meio do tratamento de uma outra ocorrência.

Para isso, eu devo acessar um formulário específico no qual poderei preencher os detalhes da ocorrência que gerou o alerta. Após preencher os campos necessários e confirmar o envio, todos os membros da equipe selecionados devem ser notificados imediatamente.

**Critérios de aceitação:**

- Deve haver um botão na tela inicial especificamente para a criação direta de um alerta interno;
- Deve haver um formulário claro e intuitivo para criar um alerta interno;
- Todos os membros da equipe selecionados devem ser notificados imediatamente após o envio do alerta;
- A ocorrência que gerou o alerta deve ser claramente descrita na mensagem de notificação;
- Cada membro da equipe deve confirmar ou recusar sua disponibilidade para assumir a responsabilidade pela ocorrência antes que outra pessoa possa fazê-lo;
- Somente um membro da equipe pode assumir a responsabilidade pela ocorrência geradora do alerta interna;
- O sistema deve registrar quem assumiu a responsabilidade pela ocorrência e quando isso ocorreu.

**Tasks:** 

- [ ] Criar formulário para criação de alerta interno (app);
- [ ] Configurar notificação imediata para todos os membros da equipe selecionados quando o alerta for criado (backend);
- [ ] Incluir a descrição clara da ocorrência geradora do alerta na mensagem de notificação (backend);
- [ ] Desenvolver sistema que permita cada membro da equipe confirmar ou recusar sua disponibilidade para assumir a responsabilidade pela ocorrência antes que outra pessoa possa fazê-lo (backend);
- [ ] Implementar sistema que registre quem assumiu a responsabilidade pela ocorrência e quando isso ocorreu (backend).
