### ISSUE TITLE
Fazer login

### ISSUE THREAD

**Issue by leonardo-kazu** [HUMAP-FireAlert/docs#2]
Como brigadista gostaria de poder acessar a aplicação utilizando minhas credenciais (email e senha) e acessar as funcionalidades exclusivas da minha conta, para que eu possa criar novas ocorrências e acompanhar os status das ocorrências em que estou envolvido.

**Critérios de aceitação:**

- Ao abrir o aplicativo, deve ser exibida uma splash art com as logos apropriadas.
- A tela inicial deve permitir ao usuário escolher entre fazer login ou solicitar acesso #1 (caso ainda não tenha uma conta registrada).
- Caso o usuário já tenha uma conta registrada, deve ser possível inserir suas credenciais (email e senha) para concluir o login.
- Após o login, o usuário deve ter acesso a tela inicial.
- O aplicativo deve fornecer feedback claro e preciso sobre o estado da autenticação, seja ela bem-sucedida ou malsucedida.
- Os dados de login do usuário devem ser armazenados com segurança e só podem ser acessados pelo próprio usuário.
- O endpoint utilizado para o login/autenticação deve ser seguro e protegido contra ataques maliciosos.
- Os email do login deve ser armazenado para que o usuário possa **relogar** com mais facilidade 

**Tasks:**

- [x] [Implementar a splash screen de boas vindas](https://github.com/HUMAP-FireAlert/app/issues/5)
- [x] [Implementar a tela de login armazenando token de acesso](https://github.com/HUMAP-FireAlert/app/issues/6)
- [x] [Criar um endpoint para a autenticação de usuários](https://github.com/HUMAP-FireAlert/backend/issues/4)
- [x] [Criar cache local de informações de login](https://github.com/HUMAP-FireAlert/app/issues/8)
