### ISSUE TITLE
Fazer logout

### ISSUE THREAD

**Issue by leonardo-kazu** [HUMAP-FireAlert/docs#3]
Como  brigadista logado, eu gostaria de ter a opção de fazer logout dentro da aplicação para sair com segurança e manter meus dados salvos para fazer login mais rapidamente no futuro. Para isso, as seguintes condições devem ser atendidas:

**Critérios de aceitação:**

- O sistema deve fornecer um botão de logout claro e facilmente acessível na interface do usuário.
- Ao clicar no botão de logout, o sistema deve limpar todas as informações de autenticação do usuário e encerrar a sessão atual.
- Os dados do usuário, como e-mail, devem ser mantidos em cache de maneira para que eles sejam preenchidos automaticamente na próxima vez que o usuário fizer login.
- Todas as informações de autenticação devem ser protegidas adequadamente para garantir que nenhum terceiro possa acessá-las ou usá-las indevidamente.
- Um endpoint de logout seguro deve ser criado no backend para tratar a solicitação de logout do usuário.

**Tasks:**

- [x] [Criar um botão de logout](https://github.com/HUMAP-FireAlert/app/issues/7)
- [x] [Implementar um cache local de informações de login](https://github.com/HUMAP-FireAlert/app/issues/8)
- [x] [Criar um endpoint de logout](https://github.com/HUMAP-FireAlert/backend/issues/5)
