### ISSUE TITLE
Criar ocorrência com informações obrigatórias

### ISSUE THREAD

**Issue by leonardo-kazu** [HUMAP-FireAlert/docs#4]
Como brigadista, preciso ser capaz de criar novas ocorrências relacionadas à emergencias de risco a vida ou dano imediato a estrutura do hospital para que os membros da equipe de liderança sejam capas de trata-las e tomarem medidas para manter a segurança do hospital.

**Critérios de aceitação:**

- O app deve ter a opção "Criar Ocorrência" na tela inicial, que leva diretamente ao formulário de criação de ocorrências.
- O formulário de criação de ocorrências deve conter uma seleção de categoria para ajudar a identificar rapidamente o tipo de emergência.
- O formulário deve incluir os campos obrigatórios:
> - Categoria;
> - Localização;
> - Descrição;
- Ao enviar uma nova ocorrência, a equipe de liderança do hospital deve receber uma notificação imediata com os detalhes da ocorrência, incluindo a categoria, localização e descrição.
- Todas as informações relacionadas às ocorrências devem ser armazenadas com segurança no banco de dados e protegidas adequadamente.
- Uma vez que eu tenha preenchido todos os campos necessários, eu devo ser capaz de enviar a ocorrência para a equipe de liderança do hospital, que receberá uma notificação imediata sobre a nova ocorrência.

**Tasks:**

- [x] [Melhorias visuais na tela inicial do app](https://github.com/HUMAP-FireAlert/app/issues/16)
- [x] [Criar formulário de criação de ocorrência](https://github.com/HUMAP-FireAlert/app/issues/17)
- [x] [Criar endpoint para envio da ocorrência](https://github.com/HUMAP-FireAlert/backend/issues/17)
>- [ ] [Implementar push notifications no app](https://github.com/HUMAP-FireAlert/app/issues/18)
>- [ ] [Disparar notificações a partir de nova ocorrência (backend)](https://github.com/HUMAP-FireAlert/backend/issues/18)
