### ISSUE TITLE
Ver detalhes da ocorrência (Equipe de Liderança)

### ISSUE THREAD

**Issue by leonardo-kazu** [HUMAP-FireAlert/docs#7]
Como membro da equipe de liderança eu gostaria de visualizar as informações básicas do brigadista que criou a ocorrência assim como também as informações da própria ocorrência, para que então eu possa entrar em contato com ele se necessário e resolver o problema da maneira mais rápida possível. 

**Criterios de aceitação:**

- A tela de tratamento da ocorrência deve exibir as informações básicas do brigadista que criou a ocorrência:
> - Nome;
> - Setor;
> - Contato.
- A data e hora da criação da ocorrência devem ser exibidas na tela de tratamento da ocorrência.
- As informações básicas sobre a ocorrência, como localização, descrição e categoria atribuída pelo brigadista, devem ser exibidas na tela de tratamento da ocorrência.
- O número de telefone do brigadista deve ser exibido na tela de tratamento da ocorrência e um botão para discar o número deve estar presente. Ao clicar no botão, o aplicativo de telefone deve abrir e o número deve ser discado automaticamente.
- A tela de tratamento da ocorrência deve ser exibida ao selecionar uma ocorrência na lista de ocorrências na tela de gerenciamento de ocorrências #8.
- Todas as informações devem ser exibidas claramente e de forma organizada na tela de tratamento da ocorrência, para facilitar a visualização e compreensão por parte da equipe de liderança.
- A funcionalidade de discar o número do brigadista através do aplicativo de telefone deve funcionar corretamente em todos os dispositivos compatíveis com o aplicativo.

**Tasks:**

- [x] Tratamento de hierarquia na visão de telas
- [x] Tela de visualização de todas as ocorrências
- [x] Visualização de informações do brigadista autor da ocorrência
- [x] Endpoint para ver todas as ocorrências
