### ISSUE TITLE
Fechar ocorrência com justificativa

### ISSUE THREAD

**Issue by leonardo-kazu** [HUMAP-FireAlert/docs#9]
Como **membro da equipe de liderança** quero ter a opção de fechar uma ocorrência inserindo um justificativa para que eu possamos manter um registro preciso do dos status das ocorrências e garantir que as ações necessárias sejam tomadas.

**Critérios de aceitação:**

- A opção de fechar a ocorrência deve ser exibida na tela de tratamento da ocorrência, após selecionar uma ocorrência na tela de gerenciamento de ocorrências.
- Ao selecionar a opção de fechamento da ocorrência, um campo obrigatório para justificativa deve ser exibido, permitindo ao usuário inserir informações sobre as ações tomadas para resolver a ocorrência.
- Uma vez que a justificativa seja inserida, a ocorrência deve ser marcada como "fechada" na lista geral de ocorrências.
- As informações de fechamento, incluindo data e hora de fechamento e a justificativa, devem ficar disponíveis para todos os membros da equipe de liderança visualizarem na aba de ocorrências finalizadas.
- Deve haver uma tela de confirmação de envio após preencher a justificativa.

**Tasks:**

- [x] Adicionar um botão de fechamento de ocorrência na tela de tratamento da ocorrência no app;
- [x] Criar uma tela de preenchimento de justificativa, com campos obrigatórios para preencher, com informações sobre as ações tomadas para resolver a ocorrência;
- [x] Implementar a marcação de ocorrência como "fechada" na lista geral de ocorrências no backend;
- [x] Disponibilizar a informação de fechamento, incluindo data e hora de fechamento e a justificativa, para todos os membros da equipe de liderança visualizem na aba de ocorrências finalizadas no app;
- [ ] Adicionar uma tela de confirmação de envio após preencher a justificativa no app.
